sudo: required
dist: bionic
language: go
go:
- 1.12.5
services:
- docker
deploy:
  provider: releases
  api_key:
    secure: "qWya/GlEHFT3N43/0SShflGLlyHvijhqxFi6GGYudFs0eFNFoVV4I3tOfMrUbWQnWY0POo9oFVU+tGy2WaYiBHBX964272wsOlCC36pZnCX5FOy2o+8IRksoq+KuW/jvmkAx1ZXf6mB08WtCe5A8duxoJsh80hCvySc1RExqdQovV5RM8GOSegYWssqJ/+KnNgbIQ0vvX/DtMC1/YGqXOijNgHreBi1moRc4pVPW8+h5hBFi8MCOguYASsbLk0NeW8fU7GP6asrzI1En289shCgLxmCDhFQbr+ofXk786/+AjHg89HD1SIHq9xLguERHBKnc2RzcEliu4Y/ZdTlCctPG8icwmWIVHYAnO3bDLup+WpACW1BuzbthXGrT+vjXfu/waAKSoir/ZFcGQtvrEuNL6XcToX3ZcuI/3sCsLOnGs3taqKCBEUoSBm2J2wPQRyLrbFCAON3dPe1iA6h1Lp/V7TGOIRLVJKWP6v3sWbuGQ+99WjvEeGmA9lFjIVWpRhsennCjCHiCTYhJi6LK00Ot/e60j1ubpQ+82faWW+joQXORksCXJ28BkgcbCwTOjeobRF+5HE7Pp6sj25fg080N4Hm1nGHK3RcGj9PxSWbEjwKbTDf8J20D8Ve5ozHa4YV+ABLIdPU6lsiajvGIpeCQkfT50TUaxYaIzzfvueQ="
  on:
    tags: true
  file: "./build/fs_exporter"
  skip_cleanup: true
env:
  global:
  - secure: "hcRZ9s/3X25Vc7uSadkJo1QksC9zk39J2XB44d36nepfWyRP+DAVCu16PS9coHb/awIQnxn4KW37o0xH3dsAAFBFFR69VB6XhauxA/SlsVdxFj/zhXz7HuvPQhr9xRAgeabDj+prS1zifTfQYnoAGn2cNR8VJY4RVawtsmptcJLKiPH62VThF8TFEFkX8SBShmViwRsPgNsyKBAHTFOnkrRt9AymqgmI5fYp8CL6XlXIBCxubk66qjZuwgSCIdvvBS/A0ZFHNK+J6MRsCMSw8XG06W1KVlosR6rcGc6k0VK8LD/19ILxTTGHkvzquFG0MD61rTNaE9o2HJFiSYnv6MLSh9ccj7ppmSKsytXUYFMHpMI/vYV5jHGWPOnqy3cD57CyZ1i+kCHyMysZZ3jzflWmtblHtS2KV/m1ntB7/xnjSSeTiUK/7w1NxrQCfzFXyUDjrX4iqBX11uIeth6cPSlUvlJ6q7xAkN6J+hTDYkPBUgYjVP/GXtaJAN+FFOLqzPSgRKFP2kei+Ca764Y9GgYBoARt9q9RjpHPqqAyk0Ml82Q6OJlSwiNJ70c5vD5lvkUWYEgUFFGDLdbmViE6NonQ64FjMdPB1QRFtVbxIkHcextijbGYhdSmoudeCrq6ZkK0DY7kez+XKsHube9q9JYUcMMLLfMhq0wO7ORduaE="
  - secure: "K9gulZ5NBY/fBjGpFw2gO5UP3SlxguqMIw+zKf2rwTPv2AvPjNs8hrRiJVm0m1IFWvW8ZPjhfThHpborDy8aT1PaAo7lydznpew8itgd1wGSAbxgIYBIwvMe+H372fGvji5MwmRIpbgWMxwrLMfa/aFl3ZxJYWfc27eym6CCjMA2gwmWCVl0zRzc6lx7bcB2pjo+llDXQbRhcUUj/qpB8AydcDTyQnxmmgVk2wC/zWhssDR0H569tBROjhNfF15QY6dalkgtDf+zOU+tjVw2qDEYjKlLy4ZmvFn4xOGrZfBriF9069cFQRGeDYcGesxHjeYlmSdtjbKetL8mQo5OqeXCWa1dmyzW7Lq/W8pIcWQJstxZPJHMfA0oFnqrh3hpy5YMyo7Gt1l3qKSRAdQLZ9oGtWAXZKsKjbgeMznR1W/SsPqIAnbQYM5WPXhuVGylqv0kRg1y+bRJaHlUOWZ8hMsire6RgXEX8ewHNP8qA/bd4ySAx5t3kT5MnJ//z5oLb4MhAAcKM1Xs6Jws4PCoQFg9RmsCfMX4ypzxAj5qHdTNNj8YKXF3NLdx7Axi7WwNjLYI26lZT52x4fqfij66a5/5YMbqsXhoc6+OINAuC9GICxfmo5Ir2MnG3jhDfnr6JVDQqRMlDNcXxuUe7BHq8e6VqunBqqjaIO9v+qu7OAo="
script:
- "./dockerBuild.sh"
- "./build.sh"
